# STEP 1:import libraries

In [96]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# step 2: import data set

In [97]:
dataset=pd.read_csv('vehicle.data')

In [98]:
dataset

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

# step 3: to create feature matrix(X) and dependent  variable vector(Y)

In [99]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

# Step 4: replacing missing data

# Step 5: Encoding

# Feature Matrix using Ordinal encoding

In [100]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
X=np.array(oe.fit_transform(X))
X

array([[3., 3., 0., 0., 2., 2.],
       [3., 3., 0., 0., 2., 0.],
       [3., 3., 0., 0., 1., 1.],
       ...,
       [1., 1., 3., 2., 0., 1.],
       [1., 1., 3., 2., 0., 2.],
       [1., 1., 3., 2., 0., 0.]])

In [101]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=np.array(le.fit_transform(Y))
Y

array([2, 2, 2, ..., 2, 1, 3])

# step 6: spliting to data  set into training data set and testing data set

In [102]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

In [103]:
Xtrain

array([[1., 2., 2., 1., 1., 2.],
       [0., 0., 3., 1., 1., 0.],
       [3., 2., 3., 0., 1., 1.],
       ...,
       [2., 2., 0., 1., 0., 0.],
       [3., 2., 0., 2., 2., 0.],
       [2., 0., 3., 1., 2., 1.]])

In [104]:
Xtest

array([[1., 0., 0., 2., 1., 1.],
       [0., 0., 1., 2., 0., 0.],
       [0., 0., 3., 0., 1., 0.],
       ...,
       [3., 1., 2., 1., 2., 1.],
       [3., 3., 1., 2., 1., 0.],
       [3., 3., 3., 1., 1., 0.]])

# step 7: feature scaling

In [105]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtrain=sc.fit_transform(Xtrain)
Xtest=sc.fit_transform(Xtest)

# step B:Build my classification model

# step 1: Training the classification model

In [106]:
from  sklearn.linear_model import LogisticRegression
LoR=LogisticRegression(random_state=0)
LoR.fit(Xtrain,Ytrain)

LogisticRegression(random_state=0)

# step 2: testing the classification model

In [107]:
Yestimated=LoR.predict(Xtest)

In [108]:
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[2, 2],
       [3, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [0, 3],
       [2, 2],
       [2, 0],
       [2, 3],
       [3, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 3],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 3],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 2],
       [2, 2],
       [0, 0],
       [0, 2],
       [2, 1],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [3, 3],
       [2, 2],
       [2, 1],
       [2, 2],
       [2, 2],
       [2,

# confusion matrix:

In [109]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Ytest,Yestimated)

In [110]:
cm

array([[ 13,   0,  57,   3],
       [  2,   0,  11,   0],
       [ 20,   0, 219,   0],
       [  9,   0,  10,   2]], dtype=int64)

In [111]:
from sklearn.metrics import accuracy_score,precision_score
from sklearn.metrics import classification_report
print(classification_report(Ytest,Yestimated))

              precision    recall  f1-score   support

           0       0.30      0.18      0.22        73
           1       0.00      0.00      0.00        13
           2       0.74      0.92      0.82       239
           3       0.40      0.10      0.15        21

    accuracy                           0.68       346
   macro avg       0.36      0.30      0.30       346
weighted avg       0.60      0.68      0.62       346



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# NAIVE BAYES

In [112]:
from  sklearn.naive_bayes import GaussianNB
NB=GaussianNB()
NB.fit(Xtrain,Ytrain)
Yestimated=NB.predict(Xtest)
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[2, 2],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [0, 3],
       [2, 2],
       [2, 0],
       [2, 3],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 0],
       [0, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 0],
       [2, 3],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 3],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 2],
       [2, 1],
       [2, 0],
       [0, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 3],
       [2, 2],
       [2, 1],
       [2, 2],
       [2, 2],
       [2,

In [113]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score
from sklearn.metrics import classification_report
print(classification_report(Ytest,Yestimated))

              precision    recall  f1-score   support

           0       0.50      0.33      0.40        73
           1       0.00      0.00      0.00        13
           2       0.78      0.97      0.86       239
           3       0.00      0.00      0.00        21

    accuracy                           0.74       346
   macro avg       0.32      0.32      0.31       346
weighted avg       0.64      0.74      0.68       346



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [114]:
print('for NB')
print("Training set score: {}".format(NB.score(Xtrain,Ytrain)))
print("Testing set score: {}".format(NB.score(Xtest,Ytest)))
print('for LR')
print("Training set score: {}".format(LoR.score(Xtrain,Ytrain)))
print("Testing set score: {}".format(LoR.score(Xtest,Ytest)))

for NB
Training set score: 0.6328747284576394
Testing set score: 0.7369942196531792
for LR
Training set score: 0.6929761042722665
Testing set score: 0.6763005780346821


In [115]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Ytest,Yestimated)
cm

array([[ 24,   0,  49,   0],
       [  5,   0,   8,   0],
       [  8,   0, 231,   0],
       [ 11,   0,  10,   0]], dtype=int64)

# DECISION TREE

In [116]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier(criterion='entropy',random_state=0)
DT.fit(Xtrain,Ytrain)
Ypred=DT.predict(Xtest)

In [117]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,Ypred))

0.976878612716763


In [118]:
print("for decision tree")
print("Training set score: {}".format(DT.score(Xtrain,Ytrain)))
print("Testing set score: {}".format(DT.score(Xtest,Ytest)))

for decision tree
Training set score: 1.0
Testing set score: 0.976878612716763


In [119]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Ytest,Ypred)
cm

array([[ 71,   0,   2,   0],
       [  2,  11,   0,   0],
       [  3,   0, 236,   0],
       [  1,   0,   0,  20]], dtype=int64)

# RANDOM FOREST

In [120]:
from sklearn.ensemble import RandomForestClassifier
RF= RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=0)
RF.fit(Xtrain,Ytrain)
Ypre=RF.predict(Xtest)

In [121]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,Ypre))

0.9508670520231214


In [122]:
print("for decision tree")
print("Training set score: {}".format(RF.score(Xtrain,Ytrain)))
print("Testing set score: {}".format(RF.score(Xtest,Ytest)))

for decision tree
Training set score: 1.0
Testing set score: 0.9508670520231214


In [123]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Ytest,Ypre)
cm

array([[ 65,   0,   8,   0],
       [  2,  11,   0,   0],
       [  6,   0, 233,   0],
       [  1,   0,   0,  20]], dtype=int64)